apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-db
  namespace: default
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store
  target:
    name: app-db
    creationPolicy: Merge

  data:
  - secretKey: username
    remoteRef:
      key: apps/database         # vault path: secret/data/apps/database
      property: username

  - secretKey: password
    remoteRef:
      key: apps/database
      property: password
