apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-store
spec:
  provider:
    vault:
      server: "https://vault.vault.svc:8200"
      path: "secret"           # KV v2: secret/data/*
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: default
          key: token
