#ENC[AES256_GCM,data:rP/NcZNBHEhtDC9gic70w2YNVxL/tHU3R6+GelsJXxIP+whzRLffNWdUa0E8QZVuKXo=,iv:M/NLCGweIu/zNIhtDfdWFhSH3OzD40gVywtvyHprB1U=,tag:N2eb1IlA/ScoCrNGCp+Oaw==,type:comment]
apiVersion: ENC[AES256_GCM,data:p70=,iv:CAtUvi7bDWEz8yV/aXOR7OqasdW6/BreForum2RQcEA=,tag:eQuNvA5LyRQmFchqtif8MA==,type:str]
kind: ENC[AES256_GCM,data:ym+QuIyC,iv:IRCJVRIZjMBs409gAt8Ki2jMQuu8qgdjjA/00yGHhqs=,tag:LRT/adThWHIJdylnz1FGKA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/agxZU4Rn56hSPDA,iv:4DlsNizE1OnPx1tO1A+6GDNPAgJXxJAMLhexuDC/OV8=,tag:Ti4uxL3EY1m+hVGVW/89wA==,type:str]
    annotations:
        vault-sync/path: ENC[AES256_GCM,data:dW8n56YuIow8xcfDLy6d947gg7gZWkyiDA==,iv:G4UL9NqPDFmPRVCSBzpEYBJbMTZ5CYsv6QaZJuSGNRo=,tag:DiJC0QktFMiqlwoOa80/8g==,type:str]
type: ENC[AES256_GCM,data:2BvJb+Hi,iv:lV107H9USouSdEBLQeRoLEIB4sWYP6hb8y9M2X3KjE0=,tag:Wgvwp0JbzmSyzGQ+J/YGrw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:+blu8Fk=,iv:u9soTRcyRUwW+/IYtqFQWk9DXssEmSN4RjEJp6YDiaw=,tag:Yo9/FU6kxgiKpTVMbVp/2Q==,type:str]
    password: ENC[AES256_GCM,data:dUwDr+dHAvXF,iv:zp3A558j5n7ot8ODUtFsoeesgrQNc5MQIdXQ0TIaYC8=,tag:WrODYa0KMrm1Thc11q6qHA==,type:str]
    host: ENC[AES256_GCM,data:iYs0VQEW1rYlaac2TVGa+XCj/3c=,iv:BYi6Qu3Gs3j5ZA3kaBMn7K9eOuzoL3bUx7Zbt37VkM0=,tag:9SsFO7jMZbgku/SK6LOASA==,type:str]
sops:
    age:
        - recipient: age16q9p72g5vqzj4p97qfuzfkqvympwhyk9kl0rs7wksqexgj7fyp2shvwmya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SUltK1V1RlBMNW9QVnY2
            cFNmMzczaFlRMGp1ZmkycmtDL0VWYXUwOEhBCnBkWldBbGlkUWc3bG1RRXpodTRy
            VFVReHliZytuRlY0aUdMWU83WktEVkkKLS0tIGZ5dnlscXgvZnk0RWVIQldZcnVO
            YUQ2WGZtQW1iRmkwRW9FSGVDRFpkd0UK9PGLTqVxIAKOvimkqtxgnZap693hBJw2
            Zg4BMlwjk38DJnJLNDqUI9MVzc7rjBkmXjYkmb8R8tDmwEL/id86aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T14:43:18Z"
    mac: ENC[AES256_GCM,data:VKRzCqvBbcsIAxPPm/fnYm3r5va0+6u1pmnnasz2RD2thZUJyV+Ec1MO0YqAR/c17uepXDxV6c2STnSyOfhD7csDYIPCuei9/cTk0q8IEoaIsbKCHt9XW7kGGx7+oWGEp5krB3hzmGGPx49znSS+Y7KkoszO1+fm6qw8fVNbizc=,iv:Y8dNWYBdpgzMjtWw9PCA1HT+q9dCRmSK49xSvInCUkc=,tag:NEA8LT2/FxaN/eskx6nt6A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
