apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops-vault-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:artsiom494-lab/test.git
    targetRevision: HEAD
    path: sops-age-key
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true