apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:your-org/vault-secret-sync.git
    targetRevision: main
    path: .
    plugin:
      name: kustomize
      parameters:
        - name: buildOptions
          value: "--enable-alpha-plugins --enable-exec"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true